name: Maven CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 15 * * 0"

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: # for EnricoMi/publish-unit-test-result-action
      checks: write
      pull-requests: write # for comment_mode
      contents: read # only for private repository
      issues: read # only for private repository
    strategy:
      matrix:
        java-version: [11]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup java environment
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: maven

      - name: Lint java code by checkstyle
        uses: nikitasavinov/checkstyle-action@79490c0fdcc3ab5dd2b50a0e82a5bfc4fe63f0a9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-check"

      - name: Build by maven
        run: mvn -B package --file pom.xml

      - name: Publish junit report to PR
        uses: EnricoMi/publish-unit-test-result-action@30eadd5010312f995f0d3b3cff7fe2984f69409e
        if: ${{ env.os == 'ubuntu-latest' }} # linux is only supported
        with:
          check_name: junit test results
          files: target/surefire-reports/**/*.xml

      - name: Move target files
        run: mkdir staging && cp target/*.jar staging

      - name: Upload junit report to artifact
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
        with:
          name: Package
          path: staging

  sast-codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["java"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Initialize CodeQL
        uses: github/codeql-action/init@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          languages: ${{ matrix.language }}

      - name: Build automatically
        uses: github/codeql-action/autobuild@cdcdbb579706841c47f7063dda365e292e5cad7a

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@cdcdbb579706841c47f7063dda365e292e5cad7a
